apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-router
  labels:
    app.kubernetes.io/name: query-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: query-router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: query-router
    spec:
      imagePullSecrets:
        - name:   nvcrio
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name:  query-router
        image:  nvcr.io/ea-botmaker/dev/generative-ai-examples:v0.1.0-chain-server
        command:
        - uvicorn
        - chain_server.server:app
        - --port
        - "8081"
        - --host
        - 0.0.0.0
        env: 
        - name: APP_MILVUS_URL
          value: http://milvus:19530
        - name: APP_TRITON_MODELNAME
          value: ensemble
        - name: APP_TRITON_SERVERURL
          value: triton:8001
        ports:  
        - containerPort: 8081
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        resources:
          limits:
            {{ .Values.query.gpu.type }}: {{ .Values.query.gpu.count }} 
---
apiVersion: v1
kind: Service
metadata:
  name:  query
spec:
  selector:
    app.kubernetes.io/name: query-router
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081